import Header from 'src/components/Header'
import { Inter } from 'next/font/google'
import Footer from 'src/components/Footer'
import './globals.css'

const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter"
 })

export const metadata = {
  title: 'Epic Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.variable} font-sans`}>
        <div className='min-h-screen flex flex-col'>
          <Header></Header>
          <main className='flex-grow bg-[#f7f7f7]'>
           {children}
          </main>
          <Footer></Footer>
        </div>
        </body>
    </html>
  )
}
